# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         SMS-AQL
version:      0.02
version_from: lib/SMS/AQL.pm
installdirs:  site
requires:
  LWP::UserAgent: 0
  HTTP::Request:  0
distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
